import Foundation
import SwiftUI

final class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: Language = .english
    @AppStorage("selectedLanguage") private var storedLanguage: String = "en"
    
    var hasUserSetLanguage: Bool {
        UserDefaults.standard.string(forKey: "selectedLanguage") != nil
    }
    
    enum Language: String, CaseIterable, Identifiable {
        case english = "en"
        case spanish = "es"
        case french = "fr"
        case german = "de"
        case chinese = "zh"
        case japanese = "ja"
        
        var id: String { rawValue }
        
        var displayName: String {
            switch self {
            case .english: return "English"
            case .spanish: return "Español"
            case .french: return "Français"
            case .german: return "Deutsch"
            case .chinese: return "中文"
            case .japanese: return "日本語"
            }
        }
        
        var nativeName: String {
            switch self {
            case .english: return "English"
            case .spanish: return "Español"
            case .french: return "Français"
            case .german: return "Deutsch"
            case .chinese: return "中文"
            case .japanese: return "日本語"
            }
        }
    }
    
    private init() {
        if let savedLanguageCode = UserDefaults.standard.string(forKey: "selectedLanguage"),
           let language = Language(rawValue: savedLanguageCode) {
            currentLanguage = language
            storedLanguage = savedLanguageCode
        } else {
            currentLanguage = .english
            storedLanguage = Language.english.rawValue
        }
        
        UserDefaults.standard.set([currentLanguage.rawValue], forKey: "AppleLanguages")
        UserDefaults.standard.synchronize()
    }
    
    func setLanguage(_ language: Language) {
        DispatchQueue.main.async { [weak self] in
            self?.currentLanguage = language
            self?.storedLanguage = language.rawValue
        }
        
        UserDefaults.standard.set([language.rawValue], forKey: "AppleLanguages")
        UserDefaults.standard.synchronize()
    }
    
    func localizedString(_ key: String) -> String {
        return localizedStrings[currentLanguage]?[key] ?? localizedStrings[.english]?[key] ?? key
    }
    
    private let localizedStrings: [Language: [String: String]] = [
        .english: [
            "recordings": "Recordings",
            "record_call": "Record Call",
            "transcripts": "Transcripts",
            "settings": "Settings",
            
            "no_recordings": "No Recordings Yet",
            "your_recordings_appear": "Your recorded calls will appear here",
            "tap_record": "Tap the Record Call tab to get started",
            "all": "All",
            "today": "Today",
            "week": "Week",
            "search_recordings": "Search recordings...",
            
            "call_recording": "Call Recording",
            "date": "Date",
            "time": "Time",
            "duration": "Duration",
            "transcript": "Transcript",
            "cloud_sync": "Cloud Sync",
            "available": "Available",
            "uploaded": "Uploaded",
            "play_recording": "Play Recording",
            "pause": "Pause",
            "play": "Play",
            "share": "Share",
            "delete": "Delete",
            "cancel": "Cancel",
            "delete_recording": "Delete Recording",
            "delete_recording_message": "Are you sure you want to delete this recording? This action cannot be undone.",
            "back": "Back",
            "recording": "Recording",
            "recording_id": "Recording ID",
            
            "no_transcripts": "No Transcripts Yet",
            "transcript_available_premium": "Transcript available with Premium",
            "transcript_not_available": "Transcript not available",
            "synced": "Synced",
            "transcripts_unlock_ai": "Unlock the power of AI transcription",
            "transcripts_will_appear_here": "Your transcripts will appear here",
            "transcripts_first_recording_hint": "Make your first recording to see your transcripts here.",
            "transcripts_feature_ai_title": "AI-Powered Transcriptions",
            "transcripts_feature_ai_subtitle": "Convert calls to searchable text instantly",
            "transcripts_feature_search_title": "Smart Search",
            "transcripts_feature_search_subtitle": "Find any conversation in seconds",
            "transcripts_feature_export_title": "Export & Share",
            "transcripts_feature_export_subtitle": "Save transcripts as text files",
            "start_free_trial": "Start your 3-day free trial",
            "record_first_call": "Record your first call",
            "transcripts_auto_generated": "Transcripts will be generated automatically\nafter each recording",
            "premium_active": "Premium Active",
            "unlimited_transcripts": "Unlimited Transcripts",
            "generating_transcript": "Generating transcript",
            "copy": "Copy",
            "copied": "Copied!",
            
            "profile": "Profile",
            "language": "Language",
            "privacy_security": "Privacy & Security",
            "subscription": "Subscription",
            "legal": "Legal",
            "account": "Account",
            "notifications": "Notifications",
            "push_notifications": "Push Notifications",
            "email_notifications": "Email Notifications",
            "data_encryption": "Data Encryption",
            "end_to_end_encrypted": "End-to-end encrypted",
            "privacy_policy": "Privacy Policy",
            "terms_service": "Terms of Service",
            "current_plan": "Current Plan",
            "free_plan": "Free Plan",
            "premium_plan": "Premium Plan",
            "upgrade_premium": "Upgrade to Premium",
            "delete_data": "Delete Data",
            "delete_data_message": "This action will delete all your recorded calls and data. Are you sure you want to continue?",
            "delete_data_success": "All data deleted successfully",
            "done": "Done",
            "edit": "Edit",
            "user": "User",
            "no_phone_number": "No phone number",
            "ok": "OK",
            "notification_error": "Notification Error",
            "data_usage": "Data Usage",
            "help_support": "Help & Support",
            "unlock_premium_features": "Unlock Premium Features",
            "unlock_premium_subtitle": "Get unlimited recordings and transcripts",
            "unlimited_recordings": "Unlimited recordings",
            "full_transcripts": "Full transcripts",
            "cloud_backup": "Cloud backup",
            "priority_support": "Priority support",
            "try_3_days_free": "Try 3 Days Free",
            "subscription_then": "Then %@",
            "premium": "Premium",
            
            "welcome_back": "Welcome Back",
            "sign_in_account": "Sign in to your account",
            "create_account": "Create Account",
            "sign_up_started": "Sign up to get started",
            "continue_guest": "Continue as Guest",

            "incoming_call": "Incoming Call",
            "outgoing_call": "Outgoing Call",
            "loading_service_number": "Loading service number...",
            "unable_make_call": "Unable to make phone call on this device",
            "record_incoming_calls": "Record Incoming Calls",
            "incoming_steps_intro": "When you receive a call, follow these steps:",
            "incoming_step_1": "Answer the incoming call",
            "incoming_step_2": "Tap 'Add Call' on your phone",
            "incoming_step_3": "Call our recording service",
            "incoming_step_4": "Merge the calls - recording starts automatically",
            "incoming_step_2_app": "Open the app and tap the green phone button to call our service",
            "record_outgoing_calls": "Record Outgoing Calls",
            "outgoing_steps_intro": "Follow these steps to record your call:",
            "outgoing_step_1": "Call our recording service first",
            "outgoing_step_2": "Tap 'Add Call' on your phone",
            "outgoing_step_3": "Call the person you want to record",
            "outgoing_step_4": "Merge the calls - recording starts automatically",
            "call_our_service": "Call Our Service",
            "recording_merge_warning": "Recording starts automatically when calls are merged",
            "record_calls_title": "Record Your Call",
            "record_steps_intro": "Enter a number below and follow these steps to record:",
            "record_step_1": "Enter the phone number you want to call",
            "record_step_2": "Tap Call, then tap 'Add Call' and dial our recording service",
            "record_step_3": "Merge the calls – recording starts automatically",
            "phone_number_placeholder": "Phone number",
            "call": "Call",
            "record_step1_call_service": "Step 1: Call our recording service first",
            "record_then_return": "Step 2: Then return to the app and call the person you need, or pick a contact.",
            "record_step2_call_or_pick": "Step 2: Enter a number or pick from contacts",
            "pick_contact": "Pick contact",

            "tutorial_page1_title": "Call our recording service first",
            "tutorial_page1_body": "Tap \"Call our service\" to dial the recording line. Stay on the call, then return to the app.",
            "tutorial_page2_title": "Then call the number or pick a contact",
            "tutorial_page2_body": "Back in the app, enter the phone number on the keypad or tap \"Pick contact\" to choose from your contacts. Then tap the green call button.",
            "tutorial_page3_title": "Merge the calls",
            "tutorial_page3_body": "Merge the two calls together. Recording starts automatically—no extra steps needed.",
            "record_step3_merge": "Step 3: Merge the calls\n\nMerge the two calls together. Recording starts automatically—no extra steps needed.",
            "how_to_record": "How to record",

            "edit_profile": "Edit Profile",
            "edit_profile_subtitle": "Edit your profile name",
            "full_name": "Full Name",
            "enter_full_name": "Enter your full name",
            "phone_number": "Phone Number",
            "save_changes": "Save Changes",
            "error": "Error",
            "profile_updated": "Profile Updated",
            "profile_updated_message": "Your profile has been updated successfully.",
            "failed_update_phone": "Failed to update phone number",
            "error_updating_phone": "Error updating phone number: %@",

            "words": "Words",
            "yes": "Yes",
            "no": "No",
            "summary": "Summary",
            "quality": "Quality",
            "clear_quality": "Clear",
            "processing": "Processing",
            "full_text": "Full Text",
            "no_summary_available": "No summary available",
            "no_summary_message": "A summary has not been generated for this recording",
            "transcript_processing_unavailable": "The transcript for this recording is being processed or unavailable",
            "share_transcript_header": "Call Recording Transcript",
            "title_label": "Title",
            "contact_label": "Contact",
            "full_transcript_label": "Full Transcript"
        ],
        .spanish: [
            "recordings": "Grabaciones",
            "record_call": "Grabar Llamada",
            "transcripts": "Transcripciones",
            "settings": "Configuración",
            
            "no_recordings": "Aún No Hay Grabaciones",
            "your_recordings_appear": "Sus llamadas grabadas aparecerán aquí",
            "tap_record": "Toque la pestaña Grabar Llamada para comenzar",
            "all": "Todas",
            "today": "Hoy",
            "week": "Semana",
            "search_recordings": "Buscar grabaciones...",
            
            "call_recording": "Grabación de Llamada",
            "date": "Fecha",
            "time": "Hora",
            "duration": "Duración",
            "transcript": "Transcripción",
            "cloud_sync": "Sincronización en la Nube",
            "available": "Disponible",
            "uploaded": "Subido",
            "play_recording": "Reproducir Grabación",
            "pause": "Pausar",
            "play": "Reproducir",
            "share": "Compartir",
            "delete": "Eliminar",
            "cancel": "Cancelar",
            "delete_recording": "Eliminar Grabación",
            "delete_recording_message": "¿Está seguro de que desea eliminar esta grabación? Esta acción no se puede deshacer.",
            "back": "Atrás",
            "recording": "Grabación",
            "recording_id": "ID de Grabación",
            "no_transcripts": "Aún No Hay Transcripciones",
            "transcript_available_premium": "Transcripción disponible con Premium",
            "transcript_not_available": "Transcripción no disponible",
            "synced": "Sincronizado",
            "transcripts_unlock_ai": "Desbloquee el poder de la transcripción con IA",
            "transcripts_will_appear_here": "Sus transcripciones aparecerán aquí",
            "transcripts_first_recording_hint": "Haz tu primera grabación para ver tus transcripciones aquí.",
            "transcripts_feature_ai_title": "Transcripciones con IA",
            "transcripts_feature_ai_subtitle": "Convierta llamadas en texto buscable al instante",
            "transcripts_feature_search_title": "Búsqueda Inteligente",
            "transcripts_feature_search_subtitle": "Encuentre cualquier conversación en segundos",
            "transcripts_feature_export_title": "Exportar y Compartir",
            "transcripts_feature_export_subtitle": "Guarde transcripciones como archivos de texto",
            "start_free_trial": "Comience su prueba gratuita de 3 días",
            "record_first_call": "Grabe su primera llamada",
            "transcripts_auto_generated": "Las transcripciones se generarán automáticamente\ndespués de cada grabación",
            "premium_active": "Premium Activo",
            "unlimited_transcripts": "Transcripciones Ilimitadas",
            "generating_transcript": "Generando transcripción",
            "copy": "Copiar",
            "copied": "¡Copiado!",
            "profile": "Perfil",
            "language": "Idioma",
            "privacy_security": "Privacidad y Seguridad",
            "subscription": "Suscripción",
            "legal": "Legal",
            "account": "Cuenta",
            "notifications": "Notificaciones",
            "push_notifications": "Notificaciones Push",
            "email_notifications": "Notificaciones por Email",
            "data_encryption": "Cifrado de Datos",
            "end_to_end_encrypted": "Cifrado de extremo a extremo",
            "privacy_policy": "Política de Privacidad",
            "terms_service": "Términos de Servicio",
            "current_plan": "Plan Actual",
            "free_plan": "Plan Gratuito",
            "premium_plan": "Plan Premium",
            "upgrade_premium": "Actualizar a Premium",
            "delete_data": "Eliminar Datos",
            "delete_data_message": "Esta acción eliminará todas sus llamadas grabadas y datos. ¿Está seguro de que desea continuar?",
            "delete_data_success": "Todos los datos eliminados correctamente",
            "done": "Hecho",
            "edit": "Editar",
            "user": "Usuario",
            "no_phone_number": "Sin número de teléfono",
            "ok": "Aceptar",
            "notification_error": "Error de notificación",
            "data_usage": "Uso de datos",
            "help_support": "Ayuda y soporte",
            "unlock_premium_features": "Desbloquear funciones Premium",
            "unlock_premium_subtitle": "Obtenga grabaciones y transcripciones ilimitadas",
            "unlimited_recordings": "Grabaciones ilimitadas",
            "full_transcripts": "Transcripciones completas",
            "cloud_backup": "Copia de seguridad en la nube",
            "priority_support": "Soporte prioritario",
            "try_3_days_free": "Prueba 3 días gratis",
            "subscription_then": "Luego %@",
            "premium": "Premium",
            "welcome_back": "Bienvenido de Nuevo",
            "sign_in_account": "Inicia sesión en tu cuenta",
            "create_account": "Crear Cuenta",
            "sign_up_started": "Regístrate para comenzar",
            "continue_guest": "Continuar como Invitado",

            "incoming_call": "Llamada Entrante",
            "outgoing_call": "Llamada Saliente",
            "loading_service_number": "Cargando número de servicio...",
            "unable_make_call": "No se puede realizar la llamada en este dispositivo",
            "record_incoming_calls": "Grabar Llamadas Entrantes",
            "incoming_steps_intro": "Cuando reciba una llamada, siga estos pasos:",
            "incoming_step_1": "Conteste la llamada entrante",
            "incoming_step_2": "Toque 'Añadir llamada' en su teléfono",
            "incoming_step_3": "Llame a nuestro servicio de grabación",
            "incoming_step_4": "Combine las llamadas: la grabación comienza automáticamente",
            "incoming_step_2_app": "Abre la app y toca el botón verde para llamar a nuestro servicio",
            "record_outgoing_calls": "Grabar Llamadas Salientes",
            "outgoing_steps_intro": "Siga estos pasos para grabar su llamada:",
            "outgoing_step_1": "Llame primero a nuestro servicio de grabación",
            "outgoing_step_2": "Toque 'Añadir llamada' en su teléfono",
            "outgoing_step_3": "Llame a la persona que desea grabar",
            "outgoing_step_4": "Combine las llamadas: la grabación comienza automáticamente",
            "call_our_service": "Llamar a Nuestro Servicio",
            "recording_merge_warning": "La grabación comienza automáticamente al combinar las llamadas",

            "record_calls_title": "Grabar tu llamada",
            "record_steps_intro": "Introduce un número y sigue estos pasos para grabar:",
            "record_step_1": "Introduce el número que quieres llamar",
            "record_step_2": "Toca Llamar, luego 'Añadir llamada' y marca nuestro servicio",
            "record_step_3": "Combina las llamadas – la grabación comienza automáticamente",
            "phone_number_placeholder": "Número de teléfono",
            "call": "Llamar",
            "record_step1_call_service": "Paso 1: Llama primero a nuestro servicio de grabación",
            "record_then_return": "Paso 2: Vuelve a la app y llama a la persona que necesites o elige un contacto.",
            "record_step2_call_or_pick": "Paso 2: Introduce un número o elige un contacto",
            "pick_contact": "Elegir contacto",

            "tutorial_page1_title": "Llama primero a nuestro servicio de grabación",
            "tutorial_page1_body": "Toca \"Llamar a Nuestro Servicio\" para marcar. Mantente en la llamada y vuelve a la app.",
            "tutorial_page2_title": "Luego llama al número o elige un contacto",
            "tutorial_page2_body": "En la app, introduce el número con el teclado o toca \"Elegir contacto\". Después toca el botón verde de llamar.",
            "tutorial_page3_title": "Combina las llamadas",
            "tutorial_page3_body": "Combina las dos llamadas. La grabación comienza automáticamente.",
            "record_step3_merge": "Paso 3: Combina las llamadas\n\nCombina las dos llamadas. La grabación comienza automáticamente.",
            "how_to_record": "Cómo grabar",

            "edit_profile": "Editar Perfil",
            "edit_profile_subtitle": "Edita el nombre de tu perfil",
            "full_name": "Nombre Completo",
            "enter_full_name": "Introduce tu nombre completo",
            "phone_number": "Número de teléfono",
            "save_changes": "Guardar Cambios",
            "error": "Error",
            "profile_updated": "Perfil Actualizado",
            "profile_updated_message": "Tu perfil se ha actualizado correctamente.",
            "failed_update_phone": "Error al actualizar el número de teléfono",
            "error_updating_phone": "Error al actualizar el número de teléfono: %@",

            "words": "Palabras",
            "yes": "Sí",
            "no": "No",
            "summary": "Resumen",
            "quality": "Calidad",
            "clear_quality": "Claro",
            "processing": "Procesando",
            "full_text": "Texto completo",
            "no_summary_available": "No hay resumen disponible",
            "no_summary_message": "No se ha generado un resumen para esta grabación",
            "transcript_processing_unavailable": "La transcripción de esta grabación se está procesando o no está disponible",
            "share_transcript_header": "Transcripción de la grabación",
            "title_label": "Título",
            "contact_label": "Contacto",
            "full_transcript_label": "Transcripción completa"
        ],
        .french: [
            "recordings": "Enregistrements",
            "record_call": "Enregistrer Appel",
            "transcripts": "Transcriptions",
            "settings": "Paramètres",
            "no_recordings": "Aucun Enregistrement",
            "your_recordings_appear": "Vos appels enregistrés apparaîtront ici",
            "tap_record": "Appuyez sur l'onglet Enregistrer pour commencer",
            "cancel": "Annuler",
            "delete_recording": "Supprimer l'enregistrement",
            "delete_recording_message": "Êtes-vous sûr de vouloir supprimer cet enregistrement ? Cette action est irréversible.",
            "welcome_back": "Bon Retour",
            "sign_in_account": "Connectez-vous à votre compte",
            "create_account": "Créer un Compte",
            "sign_up_started": "Inscrivez-vous pour commencer",
            "continue_guest": "Continuer en Invité",

            "incoming_call": "Appel entrant",
            "outgoing_call": "Appel sortant",
            "loading_service_number": "Chargement du numéro de service...",
            "unable_make_call": "Impossible de passer un appel sur cet appareil",
            "record_incoming_calls": "Enregistrer les appels entrants",
            "incoming_steps_intro": "Lorsque vous recevez un appel, suivez ces étapes :",
            "incoming_step_1": "Répondez à l'appel entrant",
            "incoming_step_2": "Appuyez sur « Ajouter un appel » sur votre téléphone",
            "incoming_step_3": "Appelez notre service d'enregistrement",
            "incoming_step_4": "Fusionnez les appels - l'enregistrement démarre automatiquement",
            "incoming_step_2_app": "Ouvrez l'app et appuyez sur le bouton vert pour appeler notre service",
            "record_outgoing_calls": "Enregistrer les appels sortants",
            "outgoing_steps_intro": "Suivez ces étapes pour enregistrer votre appel :",
            "outgoing_step_1": "Appelez d'abord notre service d'enregistrement",
            "outgoing_step_2": "Appuyez sur « Ajouter un appel » sur votre téléphone",
            "outgoing_step_3": "Appelez la personne que vous souhaitez enregistrer",
            "outgoing_step_4": "Fusionnez les appels - l'enregistrement démarre automatiquement",
            "call_our_service": "Appeler notre service",
            "recording_merge_warning": "L'enregistrement démarre automatiquement lorsque les appels sont fusionnés",

            "record_calls_title": "Enregistrer votre appel",
            "record_steps_intro": "Entrez un numéro et suivez ces étapes pour enregistrer :",
            "record_step_1": "Entrez le numéro à appeler",
            "record_step_2": "Appuyez sur Appeler, puis « Ajouter un appel » et composez notre service",
            "record_step_3": "Fusionnez les appels – l'enregistrement démarre automatiquement",
            "phone_number_placeholder": "Numéro de téléphone",
            "call": "Appeler",
            "record_step1_call_service": "Étape 1 : Appelez d'abord notre service d'enregistrement",
            "record_then_return": "Étape 2 : Revenez dans l'app et appelez la personne voulue ou choisissez un contact.",
            "record_step2_call_or_pick": "Étape 2 : Entrez un numéro ou choisissez un contact",
            "pick_contact": "Choisir un contact",

            "tutorial_page1_title": "Appelez d'abord notre service d'enregistrement",
            "tutorial_page1_body": "Appuyez sur « Appeler notre service » pour composer. Restez en ligne puis revenez dans l'app.",
            "tutorial_page2_title": "Puis appelez le numéro ou choisissez un contact",
            "tutorial_page2_body": "Dans l'app, entrez le numéro au clavier ou appuyez sur « Choisir un contact », puis sur le bouton vert d'appel.",
            "tutorial_page3_title": "Fusionnez les appels",
            "tutorial_page3_body": "Fusionnez les deux appels. L'enregistrement démarre automatiquement.",
            "record_step3_merge": "Étape 3 : Fusionnez les appels\n\nFusionnez les deux appels. L'enregistrement démarre automatiquement.",
            "how_to_record": "Comment enregistrer",

            "edit_profile": "Modifier le profil",
            "edit_profile_subtitle": "Modifiez le nom de votre profil",
            "full_name": "Nom complet",
            "enter_full_name": "Entrez votre nom complet",
            "phone_number": "Numéro de téléphone",
            "save_changes": "Enregistrer les modifications",
            "error": "Erreur",
            "profile_updated": "Profil mis à jour",
            "profile_updated_message": "Votre profil a été mis à jour avec succès.",
            "failed_update_phone": "Échec de la mise à jour du numéro de téléphone",
            "error_updating_phone": "Erreur lors de la mise à jour du numéro de téléphone : %@",

            "words": "Mots",
            "yes": "Oui",
            "no": "Non",
            "summary": "Résumé",
            "quality": "Qualité",
            "clear_quality": "Clair",
            "processing": "En cours",
            "full_text": "Texte intégral",
            "no_summary_available": "Aucun résumé disponible",
            "no_summary_message": "Aucun résumé n'a été généré pour cet enregistrement",
            "transcript_processing_unavailable": "La transcription de cet enregistrement est en cours ou indisponible",
            "share_transcript_header": "Transcription de l'enregistrement",
            "title_label": "Titre",
            "contact_label": "Contact",
            "full_transcript_label": "Transcription complète"
        ],
        .german: [
            "recordings": "Aufnahmen",
            "record_call": "Anruf Aufnehmen",
            "transcripts": "Transkripte",
            "settings": "Einstellungen",
            "no_recordings": "Noch Keine Aufnahmen",
            "your_recordings_appear": "Ihre aufgenommenen Anrufe erscheinen hier",
            "tap_record": "Tippen Sie auf Anruf Aufnehmen um zu beginnen",
            "cancel": "Abbrechen",
            "delete_recording": "Aufnahme löschen",
            "delete_recording_message": "Möchten Sie diese Aufnahme wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
            "welcome_back": "Willkommen Zurück",
            "sign_in_account": "Melden Sie sich in Ihrem Konto an",
            "create_account": "Konto Erstellen",
            "sign_up_started": "Registrieren Sie sich um zu beginnen",
            "continue_guest": "Als Gast Fortfahren",

            "incoming_call": "Eingehender Anruf",
            "outgoing_call": "Ausgehender Anruf",
            "loading_service_number": "Servicenummer wird geladen...",
            "unable_make_call": "Anruf auf diesem Gerät nicht möglich",
            "record_incoming_calls": "Eingehende Anrufe aufnehmen",
            "incoming_steps_intro": "Wenn Sie einen Anruf erhalten, folgen Sie diesen Schritten:",
            "incoming_step_1": "Nehmen Sie den eingehenden Anruf an",
            "incoming_step_2": "Tippen Sie auf „Anruf hinzufügen“ auf Ihrem Telefon",
            "incoming_step_3": "Rufen Sie unseren Aufnahmedienst an",
            "incoming_step_4": "Führen Sie die Anrufe zusammen – die Aufnahme startet automatisch",
            "incoming_step_2_app": "Öffnen Sie die App und tippen Sie auf den grünen Anruf-Button für unseren Dienst",
            "record_outgoing_calls": "Ausgehende Anrufe aufnehmen",
            "outgoing_steps_intro": "Folgen Sie diesen Schritten, um Ihren Anruf aufzunehmen:",
            "outgoing_step_1": "Rufen Sie zuerst unseren Aufnahmedienst an",
            "outgoing_step_2": "Tippen Sie auf „Anruf hinzufügen“ auf Ihrem Telefon",
            "outgoing_step_3": "Rufen Sie die Person an, die Sie aufnehmen möchten",
            "outgoing_step_4": "Führen Sie die Anrufe zusammen – die Aufnahme startet automatisch",
            "call_our_service": "Servicedienst anrufen",
            "recording_merge_warning": "Die Aufnahme startet automatisch, wenn die Anrufe zusammengeführt werden",

            "record_calls_title": "Anruf aufnehmen",
            "record_steps_intro": "Nummer eingeben und diese Schritte zum Aufnehmen befolgen:",
            "record_step_1": "Geben Sie die gewünschte Rufnummer ein",
            "record_step_2": "Tippen Sie auf Anrufen, dann „Anruf hinzufügen“ und wählen Sie unseren Dienst",
            "record_step_3": "Anrufe zusammenführen – die Aufnahme startet automatisch",
            "phone_number_placeholder": "Telefonnummer",
            "call": "Anrufen",
            "record_step1_call_service": "Schritt 1: Zuerst unseren Aufnahmedienst anrufen",
            "record_then_return": "Schritt 2: Kehren Sie in die App zurück und rufen Sie die gewünschte Person an oder wählen Sie einen Kontakt.",
            "record_step2_call_or_pick": "Schritt 2: Nummer eingeben oder Kontakt wählen",
            "pick_contact": "Kontakt wählen",

            "tutorial_page1_title": "Zuerst unseren Aufnahmedienst anrufen",
            "tutorial_page1_body": "Tippen Sie auf „Servicedienst anrufen“, um zu wählen. Bleiben Sie in der Leitung und kehren Sie dann in die App zurück.",
            "tutorial_page2_title": "Dann Nummer anrufen oder Kontakt wählen",
            "tutorial_page2_body": "In der App geben Sie die Nummer ein oder tippen auf „Kontakt wählen“, dann auf den grünen Anruf-Button.",
            "tutorial_page3_title": "Anrufe zusammenführen",
            "tutorial_page3_body": "Führen Sie die beiden Anrufe zusammen. Die Aufnahme startet automatisch.",
            "record_step3_merge": "Schritt 3: Anrufe zusammenführen\n\nFühren Sie die beiden Anrufe zusammen. Die Aufnahme startet automatisch.",
            "how_to_record": "So nehmen Sie auf",

            "edit_profile": "Profil bearbeiten",
            "edit_profile_subtitle": "Bearbeiten Sie Ihren Profilnamen",
            "full_name": "Vollständiger Name",
            "enter_full_name": "Geben Sie Ihren vollständigen Namen ein",
            "phone_number": "Telefonnummer",
            "save_changes": "Änderungen speichern",
            "error": "Fehler",
            "profile_updated": "Profil aktualisiert",
            "profile_updated_message": "Ihr Profil wurde erfolgreich aktualisiert.",
            "failed_update_phone": "Telefonnummer konnte nicht aktualisiert werden",
            "error_updating_phone": "Fehler beim Aktualisieren der Telefonnummer: %@",

            "words": "Wörter",
            "yes": "Ja",
            "no": "Nein",
            "summary": "Zusammenfassung",
            "quality": "Qualität",
            "clear_quality": "Klar",
            "processing": "Wird verarbeitet",
            "full_text": "Volltext",
            "no_summary_available": "Keine Zusammenfassung verfügbar",
            "no_summary_message": "Für diese Aufnahme wurde keine Zusammenfassung erstellt",
            "transcript_processing_unavailable": "Die Transkription dieser Aufnahme wird verarbeitet oder ist nicht verfügbar",
            "share_transcript_header": "Anrufaufnahme-Transkript",
            "title_label": "Titel",
            "contact_label": "Kontakt",
            "full_transcript_label": "Vollständiges Transkript"
        ],
        .chinese: [
            "recordings": "录音",
            "record_call": "录制通话",
            "transcripts": "转录",
            "settings": "设置",
            "no_recordings": "暂无录音",
            "your_recordings_appear": "您录制的通话将显示在这里",
            "tap_record": "点击录制通话标签开始",
            "cancel": "取消",
            "delete_recording": "删除录音",
            "delete_recording_message": "确定要删除此录音吗？此操作无法撤销。",
            "welcome_back": "欢迎回来",
            "sign_in_account": "登录您的账户",
            "create_account": "创建账户",
            "sign_up_started": "注册开始使用",
            "continue_guest": "以访客身份继续",

            "incoming_call": "来电",
            "outgoing_call": "去电",
            "loading_service_number": "正在加载服务号码...",
            "unable_make_call": "此设备无法拨打电话",
            "record_incoming_calls": "录制来电",
            "incoming_steps_intro": "接到电话时，请按以下步骤操作：",
            "incoming_step_1": "接听来电",
            "incoming_step_2": "在手机上点击「添加通话」",
            "incoming_step_3": "拨打我们的录音服务",
            "incoming_step_4": "合并通话 - 录音将自动开始",
            "incoming_step_2_app": "打开应用并点击绿色通话按钮拨打我们的服务",
            "record_outgoing_calls": "录制去电",
            "outgoing_steps_intro": "请按以下步骤录制您的通话：",
            "outgoing_step_1": "先拨打我们的录音服务",
            "outgoing_step_2": "在手机上点击「添加通话」",
            "outgoing_step_3": "拨打您要录制对象的电话",
            "outgoing_step_4": "合并通话 - 录音将自动开始",
            "call_our_service": "拨打我们的服务",
            "recording_merge_warning": "合并通话后录音将自动开始",

            "record_calls_title": "录制通话",
            "record_steps_intro": "在下方输入号码并按以下步骤录制：",
            "record_step_1": "输入您要拨打的电话号码",
            "record_step_2": "点击拨打，然后点击「添加通话」并拨打我们的录音服务",
            "record_step_3": "合并通话 – 录音将自动开始",
            "phone_number_placeholder": "电话号码",
            "call": "拨打",
            "record_step1_call_service": "第一步：先拨打我们的录音服务",
            "record_then_return": "第二步：然后返回本应用，拨打需要的号码或从通讯录选择联系人。",
            "record_step2_call_or_pick": "第二步：输入号码或选择联系人",
            "pick_contact": "选择联系人",

            "tutorial_page1_title": "先拨打我们的录音服务",
            "tutorial_page1_body": "点击「拨打我们的服务」接通录音线路。保持通话后返回本应用。",
            "tutorial_page2_title": "然后拨打号码或选择联系人",
            "tutorial_page2_body": "回到应用后，用键盘输入号码或点击「选择联系人」，再点击绿色通话按钮。",
            "tutorial_page3_title": "合并通话",
            "tutorial_page3_body": "将两路通话合并。录音将自动开始，无需其他操作。",
            "record_step3_merge": "第三步：合并通话\n\n将两路通话合并。录音将自动开始，无需其他操作。",
            "how_to_record": "如何录制",

            "edit_profile": "编辑个人资料",
            "edit_profile_subtitle": "编辑您的个人资料名称",
            "full_name": "姓名",
            "enter_full_name": "请输入您的姓名",
            "phone_number": "电话号码",
            "save_changes": "保存更改",
            "error": "错误",
            "profile_updated": "个人资料已更新",
            "profile_updated_message": "您的个人资料已成功更新。",
            "failed_update_phone": "无法更新电话号码",
            "error_updating_phone": "更新电话号码时出错：%@",

            "words": "词数",
            "yes": "是",
            "no": "否",
            "summary": "摘要",
            "quality": "质量",
            "clear_quality": "清晰",
            "processing": "处理中",
            "full_text": "全文",
            "no_summary_available": "暂无摘要",
            "no_summary_message": "此录音尚未生成摘要",
            "transcript_processing_unavailable": "此录音的转录正在处理中或不可用",
            "share_transcript_header": "通话录音转录",
            "title_label": "标题",
            "contact_label": "联系人",
            "full_transcript_label": "完整转录"
        ],
        .japanese: [
            "recordings": "録音",
            "record_call": "通話録音",
            "transcripts": "転写",
            "settings": "設定",
            "no_recordings": "録音はまだありません",
            "your_recordings_appear": "録音された通話がここに表示されます",
            "tap_record": "通話録音タブをタップして開始",
            "cancel": "キャンセル",
            "delete_recording": "録音を削除",
            "delete_recording_message": "この録音を削除してもよろしいですか？この操作は元に戻せません。",
            "welcome_back": "お帰りなさい",
            "sign_in_account": "アカウントにサインイン",
            "create_account": "アカウント作成",
            "sign_up_started": "サインアップして開始",
            "continue_guest": "ゲストとして続行",

            "incoming_call": "着信",
            "outgoing_call": "発信",
            "loading_service_number": "サービス番号を読み込み中...",
            "unable_make_call": "このデバイスでは電話をかけられません",
            "record_incoming_calls": "着信を録音",
            "incoming_steps_intro": "着信があったら、次の手順に従ってください：",
            "incoming_step_1": "着信に応答する",
            "incoming_step_2": "スマートフォンで「通話を追加」をタップ",
            "incoming_step_3": "録音サービスに電話する",
            "incoming_step_4": "通話を統合する - 録音が自動で開始されます",
            "incoming_step_2_app": "アプリを開き、緑の通話ボタンをタップしてサービスに電話",
            "record_outgoing_calls": "発信を録音",
            "outgoing_steps_intro": "通話を録音するには、次の手順に従ってください：",
            "outgoing_step_1": "まず録音サービスに電話する",
            "outgoing_step_2": "スマートフォンで「通話を追加」をタップ",
            "outgoing_step_3": "録音したい相手に電話する",
            "outgoing_step_4": "通話を統合する - 録音が自動で開始されます",
            "call_our_service": "サービスに電話",
            "recording_merge_warning": "通話を統合すると録音が自動で開始されます",

            "record_calls_title": "通話を録音",
            "record_steps_intro": "番号を入力して、以下の手順で録音してください：",
            "record_step_1": "かけたい電話番号を入力",
            "record_step_2": "「通話」をタップし、「通話を追加」で録音サービスに電話",
            "record_step_3": "通話を統合すると録音が自動で開始されます",
            "phone_number_placeholder": "電話番号",
            "call": "通話",
            "record_step1_call_service": "ステップ1：まず録音サービスに電話する",
            "record_then_return": "ステップ2：アプリに戻り、かけたい番号をダイヤルするか、連絡先から選んでください。",
            "record_step2_call_or_pick": "ステップ2：番号を入力するか連絡先から選択",
            "pick_contact": "連絡先を選択",

            "tutorial_page1_title": "まず録音サービスに電話する",
            "tutorial_page1_body": "「サービスに電話」をタップして録音ラインに発信します。通話したままアプリに戻ります。",
            "tutorial_page2_title": "番号をダイヤルするか連絡先を選択",
            "tutorial_page2_body": "アプリで番号を入力するか「連絡先を選択」をタップし、緑の通話ボタンをタップします。",
            "tutorial_page3_title": "通話を統合する",
            "tutorial_page3_body": "2つの通話を統合すると、録音が自動で開始されます。",
            "record_step3_merge": "ステップ3：通話を統合する\n\n2つの通話を統合すると、録音が自動で開始されます。",
            "how_to_record": "録音の方法",

            "edit_profile": "プロフィールを編集",
            "edit_profile_subtitle": "プロフィール名を編集",
            "full_name": "氏名",
            "enter_full_name": "氏名を入力",
            "phone_number": "電話番号",
            "save_changes": "変更を保存",
            "error": "エラー",
            "profile_updated": "プロフィールを更新しました",
            "profile_updated_message": "プロフィールが正常に更新されました。",
            "failed_update_phone": "電話番号の更新に失敗しました",
            "error_updating_phone": "電話番号の更新中にエラーが発生しました：%@",

            "words": "語数",
            "yes": "はい",
            "no": "いいえ",
            "summary": "要約",
            "quality": "品質",
            "clear_quality": "クリア",
            "processing": "処理中",
            "full_text": "全文",
            "no_summary_available": "要約はありません",
            "no_summary_message": "この録音の要約は生成されていません",
            "transcript_processing_unavailable": "この録音の転写は処理中または利用できません",
            "share_transcript_header": "通話録音の転写",
            "title_label": "タイトル",
            "contact_label": "連絡先",
            "full_transcript_label": "全文転写"
        ]
    ]
}

extension View {
    func localized(_ key: String) -> String {
        LocalizationManager.shared.localizedString(key)
    }
}
